version: '3.4'

services:
  app:
    image: goggin13/wrestling-stats:latest
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/wrestling-stats
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  gem_cache:
  db_data:
  node_modules:
