 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wrestle_bet/wrestlers", type: :request do
  
  # WrestleBet::Wrestler. As you add validations to WrestleBet::Wrestler, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WrestleBet::Wrestler.create! valid_attributes
      get wrestle_bet_wrestlers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wrestler = WrestleBet::Wrestler.create! valid_attributes
      get wrestle_bet_wrestler_url(wrestle_bet_wrestler)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wrestle_bet_wrestler_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      wrestler = WrestleBet::Wrestler.create! valid_attributes
      get edit_wrestle_bet_wrestler_url(wrestle_bet_wrestler)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WrestleBet::Wrestler" do
        expect {
          post wrestle_bet_wrestlers_url, params: { wrestle_bet_wrestler: valid_attributes }
        }.to change(WrestleBet::Wrestler, :count).by(1)
      end

      it "redirects to the created wrestle_bet_wrestler" do
        post wrestle_bet_wrestlers_url, params: { wrestle_bet_wrestler: valid_attributes }
        expect(response).to redirect_to(wrestle_bet_wrestler_url(@wrestle_bet_wrestler))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WrestleBet::Wrestler" do
        expect {
          post wrestle_bet_wrestlers_url, params: { wrestle_bet_wrestler: invalid_attributes }
        }.to change(WrestleBet::Wrestler, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post wrestle_bet_wrestlers_url, params: { wrestle_bet_wrestler: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wrestle_bet_wrestler" do
        wrestler = WrestleBet::Wrestler.create! valid_attributes
        patch wrestle_bet_wrestler_url(wrestle_bet_wrestler), params: { wrestle_bet_wrestler: new_attributes }
        wrestler.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wrestle_bet_wrestler" do
        wrestler = WrestleBet::Wrestler.create! valid_attributes
        patch wrestle_bet_wrestler_url(wrestle_bet_wrestler), params: { wrestle_bet_wrestler: new_attributes }
        wrestler.reload
        expect(response).to redirect_to(wrestle_bet_wrestler_url(wrestler))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        wrestler = WrestleBet::Wrestler.create! valid_attributes
        patch wrestle_bet_wrestler_url(wrestle_bet_wrestler), params: { wrestle_bet_wrestler: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wrestle_bet_wrestler" do
      wrestler = WrestleBet::Wrestler.create! valid_attributes
      expect {
        delete wrestle_bet_wrestler_url(wrestle_bet_wrestler)
      }.to change(WrestleBet::Wrestler, :count).by(-1)
    end

    it "redirects to the wrestle_bet_wrestlers list" do
      wrestler = WrestleBet::Wrestler.create! valid_attributes
      delete wrestle_bet_wrestler_url(wrestle_bet_wrestler)
      expect(response).to redirect_to(wrestle_bet_wrestlers_url)
    end
  end
end
