# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: dumbledore
  host: database

development:
  <<: *default
  database: dumbledore_development
  password: <%= ENV['DUMBLEDORE_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: dumbledore_test

production:
  <<: *default
  database: dumbledore_production
  password: <%= ENV["DUMBLEDORE_DATABASE_PASSWORD"] %>
